### ISSUE TITLE
Neon.2 (4.6.2) - problem during debug - pause and stop functions don't work

### ISSUE THREAD

**Issue by asier70** [gnuarmeclipse/plug-ins#167] opened 2017-01-20 14:13 UTC
Problem exists in windows with Neon.2 (4.6.2), GDB 9.2 and all plugings up to date (GnuArmEclipsePlugin, OpenOCD, gcc, stlink). Almost everything works (debug start, trace, breakpoints, resuming after breakpoint) but after clicking on pause or stop microcontroller still works. To exit this not normal situation I must stop OpenOCD (MI error info appears).
Everything works on Mars.2, also project worked on Neon.1 some time ago.

**Comment by ilg-ul** [comment] 2017-01-20 14:14
did you update the plug-ins recently?

**Comment by asier70** [comment] 2017-01-20 14:17
Yes, I did. I have GNU ARM Eclipse plug-ins v3.2.1-201701141320. Some time ago everything worked, but now after do updates in eclipse problem occurs.

**Comment by ilg-ul** [comment] 2017-01-20 14:26
sorry, with the information you provided I cannot reproduce your problem. on my mac, with GCC 5.4, GDB 7.10, latest plug-ins, latest OpenOCD, on my F4DISCOVERY board, I can halt or stop the debug session without problems.

GDB 9.2 seems not correct.

**Comment by ilg-ul** [comment] 2017-01-20 14:38
I also tested on my Win 8 x64 and I can halt or stop the debugger.

**Comment by asier70** [comment] 2017-01-20 14:54
Win 10 x64, GCC 6.2, C/C++ GDB Hardware Debugging	9.2.0.201612061315
Maybe someone else has the same problem.
Thanks for checking and help!

**Comment by ilg-ul** [comment] 2017-01-20 14:55
GCC 6.2 is not yet supported.

**Comment by asier70** [comment] 2017-01-20 15:00
GCC 6.2 2016q4 works on Mars.2 with my project.

**Comment by ilg-ul** [comment] 2017-01-20 15:02
try GCC 5.4 with Neon.2.

**Comment by asier70** [comment] 2017-01-20 20:31
I've just found eclipse bug published by Freddie Chopin, that is the same I described here:
[https://bugs.eclipse.org/bugs/show_bug.cgi?id=509788](url)

**Comment by ilg-ul** [comment] 2017-01-20 20:57
ok, thank you.

**Comment by wrljet** [comment] 2017-01-20 21:13
For what it's worth, things work correctly for me.  I think I have the same setup, GCC 5.4 with Neon.2, latest ARM plugin, *except*, I'm running OpenOCD 0.7.0.

And by the way, a HUGE thank-you, Liviu for all your work.
-Bill

**Comment by ilg-ul** [comment] 2017-01-20 21:17
you're welcome, Bill.

> OpenOCD 0.7.0.

I guess it should also work with 0.10.0

the problem seems to be caused by the combination GDB 7.12, that comes with GCC 6.x, and Neon.2.

**Comment by asier70** [comment] 2017-01-23 08:09
Liviu you were right. Thanks!
Downgrading GCC 6.2 2016q4 (GDB 7.12.0.20161204) to GCC 5.4 2016q3 (GDB 7.10.1.20160923) solves the problem.

**Comment by Amcolex** [comment] 2017-01-23 16:38
I'd just like to add that we had the same problem. Windows 10 / Eclipse Neon.2 /  GCC 6.2 2016q4 / Segger J-Link V612f.

I guess this is a CDT bug though. I'll look into downgrading to GCC 5.4.

And thank you Liviu for all your work!

**Comment by asier70** [comment] 2017-03-24 07:43
Yesterday Eclipse was updated to version Neon.3 (4.6.3). There is no problem in new version with debugging using GCC in version "6.2 2016q4" and newest "6 2017-q1-update".

**Comment by ilg-ul** [comment] 2017-03-24 07:57
great! thank you for testing.

can we close this ticket?

**Comment by asier70** [comment] 2017-03-24 08:10
I've just tested it. I think we can close this ticket.

**Closed** 2017-03-24 08:15 UTC
