### ISSUE TITLE
Eclipse Update Site Offline

### ISSUE THREAD

**Issue by MrBuddyCasino** [gnuarmeclipse/plug-ins#165] opened 2017-01-14 14:14 UTC
This URL does not work:
http://gnuarmeclipse.sourceforge.net/updates

Eclipse says there is no update site there. Did I miss anything?

**Comment by ilg-ul** [comment] 2017-01-14 14:15
http://gnuarmeclipse.github.io/blog/2016/12/02/plugins-install-issue/

**Comment by MrBuddyCasino** [comment] 2017-01-14 14:31
That worked - thanks for the quick reply!

**Comment by ilg-ul** [comment] 2017-01-14 14:33
duplicate of #151

**Closed by ilg-ul** 2017-01-14 14:33 UTC
Labels: duplicate
