### ISSUE TITLE
Unable to read repository at http://gnuarmeclipse.sourceforge.net/updates/content.xml.xz.

### ISSUE THREAD

**Issue by wiesener** [gnuarmeclipse/plug-ins#158] opened 2016-12-27 09:09 UTC
Trying to install the plugin in eclipse neon.2 under mac osx (sierra) brings the following error:

Unable to read repository at http://gnuarmeclipse.sourceforge.net/updates/content.xml.xz.

Either manually or viar marketplace did not work.

Best regards,

C.W.

**Comment by ilg-ul** [comment] 2016-12-27 09:22
duplicate of #151

**Comment by wiesener** [comment] 2016-12-27 09:25
ups sorry, google did not bring it up.
— 
Constantin Wiesener
Technische Universität Berlin,  FG Regelungssysteme (Control Systems Group)
Room: EN 204   -   Phone: +49-30-314-24094   -   Fax: +49-30-314-21137
Post: TU Berlin  -  Sek. EN 11  -  Einsteinufer 17  -  D-10587 Berlin, Germany

**Comment by ilg-ul** [comment] 2016-12-27 10:35
update to latest JDK and it should work.

**Closed** 2016-12-27 10:35 UTC

**Comment by jantje** [comment] 2016-12-27 15:50
I don't want to mix in stuff that is not my business ... but I think "known limitation" covers this issue better than "can't fix"
