### ISSUE TITLE
Unable to start a debug session after updating to Eclipse Neon.2 (4.6.2)

### ISSUE THREAD

**Issue by stf12** [gnuarmeclipse/plug-ins#156] opened 2016-12-22 07:48 UTC
### Description

The issue happens after I updated from Eclipse 4.6.1 to Eclipse 4.6.2.
Moreover I have installed the last version of:
- GNU ARM Eclipse plugin
- GNU ARM Eclipse OpenOCD
- GNU ARM Eclipse Build Tool for windows
- GNU ARM Embedded Toolchain 5-2016-q3-update 

When I try to lunch debug session of type "GDB OpenOCD Debugging", the launch sequence is blocked at 99% (Launching: Configuring GDB) and the debugger never starts.

### Steps to Reproduce

1. I use a C++ program for a NUCLEO-F410 board created using the New Project wizard.
2. I create a standard Debug configuration 
3. I launch the debug configuration

**Expected behavior:** [What you expected to happen]
I expect for the debugger to start.

**Actual behavior:** [What actually happened]
The launch sequence is blocked at 99% (Launching: Configuring GDB) and the debugger never starts.

### Versions

* [plug-in version]
3.1.1-201606210758
* [Eclipse version]
4.6.2
* [Java version]
JRE 1.8.0_111
* [operating system]
Windows 7 64 bit
* [toolchain version]
gcc-arm-none-eabi-5_4-2016q3-20160926-win32

**Comment by ilg-ul** [comment] 2016-12-22 11:08
I confirm the problem, but it seems specific to Neon and Windows, on my Mac it is ok.

As a workaround, you can try to use Mars.2.

**Comment by stf12** [comment] 2016-12-25 08:43
Ok. I will wait for the fix. If I can find some more information I will report here.

Thank you.

**Comment by ilg-ul** [comment] 2016-12-25 08:47
I informed the CDT developers. I do not know if there is anything I can do in the plug-ins, or the CDT needs to repaired, and in this case it might take a while.

**Comment by Menion2k** [comment] 2017-01-04 14:39
Problem still present with CDT 9.2 on Neon.2. The problem was also present running CDT 9.0 on Neon.2 as well

**Comment by ilg-ul** [comment] 2017-01-04 15:24
the current recommendation is to stay away from Neon and use Mars.2.

**Comment by Menion2k** [comment] 2017-01-04 15:42
Actually it was working perfectly with Neon.1 and CDT 9.0

2017-01-04 16:24 GMT+01:00 Liviu Ionescu <notifications@github.com>:

**Comment by ilg-ul** [comment] 2017-01-04 15:44
please do not reply by email, but use the web interface, or at least do not quote the original message.

**Comment by Menion2k** [comment] 2017-01-05 08:56
The problem is also present in Eclipse Oxygen + CDT milestone

**Comment by ilg-ul** [comment] 2017-01-05 09:58
> Could you share the bugzilla please?

I did not register a bugzilla yet, I used the cdt-dev list.

**Comment by johnmoule** [comment] 2017-01-05 10:18
Thanks for the info.

@Menion2k 
>  I have just wiped my Neon.2 and reinstalled the above with gnuarmeclipse 3.11 and it works perfectly (Windows Host).

Which version of CDT are you using with that?
Can I infer from this discussion that the problem appears to be not with neon.2 but with cdt9.2.0?

**Comment by Menion2k** [comment] 2017-01-05 10:31
@johnmoule I have written it in my post: CDT 9.1 and no, the problem is of Neon.2 not CDT

**Comment by mibcat** [comment] 2017-01-10 17:31
shit happens - just updated from Mars to Neon yesterday and running into the same trouble ...

**Comment by ilg-ul** [comment] 2017-01-10 17:33
the penalty for not reading the installation notes.

**Comment by mibcat** [comment] 2017-01-10 17:37
you make a good point ! ;-)

**Comment by ilg-ul** [comment] 2017-01-14 15:15
fixed in v3.2.1-201701141320

**Closed by ilg-ul** 2017-01-14 15:15 UTC
Labels: bug

**Comment by stf12** [comment] 2017-01-16 02:45
Hi Liviu,

thank you for support. I confirm that the issue is solved after updating to the new version :).

But now I have another strange issue that already happened in the past. The New Project Wizard doesn't display the STM32 Template, even if in the Eclipse "Preferences > C/C++ > New C/C++ Project Wizard" I can see them (see the below images).

Btw, I think this is my problem.

Thank you again,
Stefano


![newprojectwizard](https://cloud.githubusercontent.com/assets/6305423/21969374/28a91ae6-dbe1-11e6-9d3d-c18d93475550.PNG)

![newprojectwizard-preferences](https://cloud.githubusercontent.com/assets/6305423/21969363/19798c90-dbe1-11e6-9e55-e62cccb81827.PNG)

**Comment by ilg-ul** [comment] 2017-01-16 07:56
does your problem has anything to do with the issue subject?

for general questions, please use the project forum.

**Comment by stf12** [comment] 2017-01-16 10:23
Hi Liviu,

this problem is happening after I updated the GNU ARM plug-in to v3.2.1-201701141320. But after a first analysis, I'm quite sure that is not related with this issue and with the GNU ARM plug-in.

I'm sorry I wasted your time.

**Comment by ilg-ul** [comment] 2017-01-16 16:13
in case further investigations show that it is related, please open a separate ticket.
